// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ44nHKNM4Fy4KichjpmsDjpJeg5MDylU',
    appId: '1:370177527300:web:484a6ea3f8f5edf991af51',
    messagingSenderId: '370177527300',
    projectId: 'air-quality-app-4c34e',
    authDomain: 'air-quality-app-4c34e.firebaseapp.com',
    storageBucket: 'air-quality-app-4c34e.appspot.com',
    measurementId: 'G-SDK6PST66J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv2VZNkFFUV7XxaiIZ2t4fIBc3a3GV9AE',
    appId: '1:370177527300:android:c5a8e3cafd97093f91af51',
    messagingSenderId: '370177527300',
    projectId: 'air-quality-app-4c34e',
    storageBucket: 'air-quality-app-4c34e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq_SOjSvlZ8tW3l97zaJvIrqLj5EYg4WI',
    appId: '1:370177527300:ios:328e30e84d72616391af51',
    messagingSenderId: '370177527300',
    projectId: 'air-quality-app-4c34e',
    storageBucket: 'air-quality-app-4c34e.appspot.com',
    iosClientId:
        '370177527300-6dtgtn5rdv5hq12eadm6ln86c7ipkrn0.apps.googleusercontent.com',
    iosBundleId: 'com.example.dribbleAirApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq_SOjSvlZ8tW3l97zaJvIrqLj5EYg4WI',
    appId: '1:370177527300:ios:328e30e84d72616391af51',
    messagingSenderId: '370177527300',
    projectId: 'air-quality-app-4c34e',
    storageBucket: 'air-quality-app-4c34e.appspot.com',
    iosClientId:
        '370177527300-6dtgtn5rdv5hq12eadm6ln86c7ipkrn0.apps.googleusercontent.com',
    iosBundleId: 'com.example.dribbleAirApp',
  );
}
